export const GET_CINEMAS_SUCCESS = 'GET_CINEMAS_SUCCESS';
export const GET_CINEMAS_FAILURE = 'GET_CINEMAS_FAILURE';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILURE = 'GET_MOVIE_FAILURE';
export const GET_UPCOMING_MOVIE_SUCCESS = 'GET_UPCOMING_MOVIE_SUCCESS';
export const GET_UPCOMING_MOVIE_FAILURE = 'GET_UPCOMING_MOVIE_FAILURE';
